apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: zone2
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,zone2]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/zone2: ""
